export const courses = [
  {
    slug: "full-stack",
    index: "01",
    path: "~/courses/full-stack",
    name: "Full-Stack Web Development",
    tagline: "From an empty folder to a deployed product.",
    description:
      "Learn to design, build and ship real web applications — the same stack studios actually hire for. You'll leave with a live portfolio, not just certificates.",
    stack: [
      "HTML/CSS",
      "JavaScript",
      "React",
      "Node.js",
      "PostgreSQL",
      "Git",
      "LLM APIs",
      "Prompt Engineering",
    ],
    weeks: 12,
    level: "Beginner friendly",
    outcomes: [
      "Build responsive, production-grade UIs from scratch",
      "Design and query relational databases",
      "Build and consume REST APIs",
      "Authentication, deployment & version control",
      "Integrate LLM APIs and agents with solid prompt engineering",
      "Ship 3+ full applications for your portfolio",
    ],
  },
  {
    slug: "app-dev",
    index: "02",
    path: "~/courses/app-dev",
    name: "App Development (Flutter)",
    tagline: "One codebase. Android and iOS, done properly.",
    description:
      "Go from zero to publishing a working Flutter app on the Play Store. Built around real client-style projects, not toy exercises.",
    stack: [
      "Dart",
      "Flutter",
      "Firebase",
      "REST APIs",
      "State Management",
      "LLM APIs",
      "Prompt Engineering",
    ],
    weeks: 12,
    level: "Beginner friendly",
    outcomes: [
      "Build fluid, native-feeling mobile UIs in Flutter",
      "Connect apps to real backends & Firebase",
      "Handle state, navigation & device APIs",
      "Integrate LLM APIs and agents with solid prompt engineering",
      "Package and publish an app to the Play Store",
      "Ship a capstone app for your portfolio",
    ],
  },
];
